<?php

function imc_alba_menu() {
	$items = array();
	$items['admin/settings/imcalba'] = array(
		'title' => 'Indymedia basic settings',
		'description' => '',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('imc_alba_admin'),
		'access arguments' => array('administer site configuration'),
	);

	return $items;
}

function imc_alba_form_alter(&$form, $form_state, $form_id)
{
	/* Unfortunately necessary to make the upload module wysiwyg hack
	 * implemented in the theme work */
	if (isset($form['type']) && isset($form['#node'])) {
		$form['attachments']['wrapper']['new']['attach']['#ahah']['method'] = 'replaceAndUpdateHandlers';
		$form['attachments']['#weight'] = -1;
		$form['attachments']['#collapsed'] = false;
		$form['attachments']['#title'] = t('File and image attachments');
		$form['attachments']['#description'] = t('Changes made to the attachments are not permanent until you save this post. The first "listed" file will be included in RSS feeds. The first file will be used as the article\'s preview image.');
	}
}

function imc_alba_admin() {
	$form = array();
	$form["imc_alba_days_to_close_commenting"] = array(
		'#type' => 'select',
		'#title' => t('Close commenting to items after how long'),
		'#default_value' => variable_get("imc_alba_days_to_close_commenting", 0),
		'#options' => array(
			0 => t('Never'), 7 => t('1 week'), 30 => t('1 month'),
			60 => t('2 months'), 90 => t('3 months'), 180 => t('6 months'),
			),
		);
	$form['members'] = array(
		'#type' => 'fieldset',
		'#title' => t('Members'),
		'#collapsible' => TRUE,
	);
	$q = db_query("SELECT rid, name FROM {role}");
	$roles = array(0 => '--- ' . t('disabled') . ' ---');
	while ($a = db_fetch_array($q)) {
		$roles[$a['rid']] = $a['name'];
	}
	$form['members']['imc_alba_member_rid'] = array(
		'#type' => 'select',
		'#title' => t('Role assigned to active site \'members\''),
		'#default_value' => variable_get('imc_alba_member_rid', 0),
		'#options' => $roles,
		'#description' => t("Users of the site become members when they have contributed good articles to the site.
			Note that this role will be automatically
			added/removed from users, so don't use a role you wish
			to be permanent for some users.")
	);
	return system_settings_form($form);
}

function imc_alba_cron() {
	// update membership
	// find users who have written articles in the last year (and not the
	// last week to allow moderators time), which are still visible (not
	// hidden or deleted). These users are now members.
	$member_rid = variable_get('imc_alba_member_rid', 0);
	if ($member_rid) {
		db_query("DELETE FROM {users_roles} WHERE rid=%d", $member_rid);
		$r = db_query("SELECT u.uid FROM {users} u WHERE u.status=1 AND EXISTS (SELECT * FROM
		{node} n WHERE n.status=1 AND n.created > %d AND n.created < %d AND
		n.uid=u.uid AND n.type='article')", time()-60*60*24*365,
			time()-60*60*24*7);
		while ($a = db_fetch_array($r)) {
			db_query("INSERT INTO {users_roles} (uid, rid) VALUES (%d, %d)",
					$a['uid'], $member_rid);
		}	
	}
	$days_to_close_commenting = variable_get("imc_alba_days_to_close_commenting", 0);
	if ($days_to_close_commenting) {
		$time_ago = time() - 60*60*24*$days_to_close_commenting;
		db_query("UPDATE {node} SET comment=1 WHERE created < %d AND comment=2", $time_ago);
	}
}
