<?php
/* $Id: recaptcha.install,v 1.2.4.2.2.3.2.1 2007/12/03 16:38:56 robloach Exp $ */

/**
 * @file
 * Provides install, updated, and uninstall functions for recaptcha.
 */
 
/**
 * Implementation of hook_uninstall().
 */
function recaptcha_uninstall() {
  // Delete all the recaptcha variables and then clear the variable cache  
  db_query("delete from {variable} where name like '%s'", 'recaptcha_%');
  cache_clear_all('variables', 'cache');
}
